require("general.generalconf")
require("general.keybindings")

require("plugins.plugs")

require("pluginconf.mason")
require("pluginconf.nvim-cmp")
require("pluginconf.lsp_signature")
require("pluginconf.treesitter")
require("pluginconf.treesitter-rainbow")
require("pluginconf.treesitter-context")
require("pluginconf.everforest")
require("pluginconf.ultisnips")
require("pluginconf.vim-slime")
require("pluginconf.lualine")
require("pluginconf.nerdtree")
require("pluginconf.bufferline")
require("pluginconf.marks")
require("pluginconf.aerial")
require("pluginconf.trevj")
require("pluginconf.comment")
require("pluginconf.leap")
require("pluginconf.ccc")
