require("general.generalconf")
require("general.keybindings")

require("plugins.plugs")

require("pluginconf.aerial")
require("pluginconf.bufferline")
require("pluginconf.ccc")
require("pluginconf.comment")
require("pluginconf.everforest")
require("pluginconf.fugitive")
require("pluginconf.hop")
require("pluginconf.lsp")
require("pluginconf.lsp_signature")
require("pluginconf.lualine")
require("pluginconf.mason")
require("pluginconf.nvim-cmp")
require("pluginconf.nvimtree")
require("pluginconf.teoj")
require("pluginconf.textbook")
require("pluginconf.treesitter-context")
require("pluginconf.treesitter")
require("pluginconf.trevj")
require("pluginconf.undotree")
require("pluginconf.vim-slime")
