require("general.generalconf")
require("general.keybindings")

require("plugins.plugs")

require("pluginconf.treesitter")
require("pluginconf.treesitter-rainbow")
require("pluginconf.treesitter-context")
require("pluginconf.gruvbox")
require("pluginconf.lualine")
require("pluginconf.hop")
require("pluginconf.ultisnips")
require("pluginconf.vim-slime")
require("pluginconf.nerdtree")
require("pluginconf.revj")
require("pluginconf.bufferline")
require("pluginconf.lsp")
