return {
	require("juselara.plugins.dracula"),
	require("juselara.plugins.lualine"),
	require("juselara.plugins.comment"),
	require("juselara.plugins.which-key"),
	require("juselara.plugins.flash"),
	require("juselara.plugins.telescope"),
	require("juselara.plugins.telescope-undo"),
	require("juselara.plugins.treesitter"),
	require("juselara.plugins.treesitter-textobjs"),
	require("juselara.plugins.aerial"),
	require("juselara.plugins.trevj"),
	require("juselara.plugins.lspconfig"),
	require("juselara.plugins.cmp"),
	require("juselara.plugins.neotree"),
	require("juselara.plugins.dashboard"),
}
